# -*- coding: utf-8 -*-
"""Upgrade Python for Data Science Zero to Hero Day 1 Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-d3huMGtCLVTCT9_BDVb6DgIq50c2znC
"""

p = int(input("Enter the principle amount"))
r = int(input("Enter the interest rate"))
t = int(input("Enter the rate of time"))
Interest = p*r*t/100 
print ("Therefore, the simple interest is {}".format(Interest))